// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Automation is the predicate function for automation builders.
type Automation func(*sql.Selector)

// Macro is the predicate function for macro builders.
type Macro func(*sql.Selector)

// Procedure is the predicate function for procedure builders.
type Procedure func(*sql.Selector)
