// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AutomationColumns holds the columns for the "automation" table.
	AutomationColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "trigger", Type: field.TypeString},
		{Name: "manifest", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool},
	}
	// AutomationTable holds the schema information for the "automation" table.
	AutomationTable = &schema.Table{
		Name:       "automation",
		Columns:    AutomationColumns,
		PrimaryKey: []*schema.Column{AutomationColumns[0]},
	}
	// MacroColumns holds the columns for the "macro" table.
	MacroColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "metadata", Type: field.TypeString},
		{Name: "code", Type: field.TypeString},
	}
	// MacroTable holds the schema information for the "macro" table.
	MacroTable = &schema.Table{
		Name:       "macro",
		Columns:    MacroColumns,
		PrimaryKey: []*schema.Column{MacroColumns[0]},
	}
	// ProcedureColumns holds the columns for the "procedure" table.
	ProcedureColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "metadata", Type: field.TypeString},
		{Name: "manifest", Type: field.TypeString},
	}
	// ProcedureTable holds the schema information for the "procedure" table.
	ProcedureTable = &schema.Table{
		Name:       "procedure",
		Columns:    ProcedureColumns,
		PrimaryKey: []*schema.Column{ProcedureColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AutomationTable,
		MacroTable,
		ProcedureTable,
	}
)

func init() {
	AutomationTable.Annotation = &entsql.Annotation{
		Table: "automation",
	}
	MacroTable.Annotation = &entsql.Annotation{
		Table: "macro",
	}
	ProcedureTable.Annotation = &entsql.Annotation{
		Table: "procedure",
	}
}
