// Code generated by ent, DO NOT EDIT.

package automation

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the automation type in the database.
	Label = "automation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldTrigger holds the string denoting the trigger field in the database.
	FieldTrigger = "trigger"
	// FieldManifest holds the string denoting the manifest field in the database.
	FieldManifest = "manifest"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// Table holds the table name of the automation in the database.
	Table = "automation"
)

// Columns holds all SQL columns for automation fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldTrigger,
	FieldManifest,
	FieldEnabled,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Automation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByTrigger orders the results by the trigger field.
func ByTrigger(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrigger, opts...).ToFunc()
}

// ByManifest orders the results by the manifest field.
func ByManifest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManifest, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}
