// Code generated by ent, DO NOT EDIT.

package automation

import (
	"entgo.io/ent/dialect/sql"
	"github.pitagora/pkg/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Automation {
	return predicate.Automation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Automation {
	return predicate.Automation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Automation {
	return predicate.Automation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Automation {
	return predicate.Automation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Automation {
	return predicate.Automation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Automation {
	return predicate.Automation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Automation {
	return predicate.Automation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Automation {
	return predicate.Automation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Automation {
	return predicate.Automation(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Automation {
	return predicate.Automation(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Automation {
	return predicate.Automation(sql.FieldEQ(FieldDescription, v))
}

// Trigger applies equality check predicate on the "trigger" field. It's identical to TriggerEQ.
func Trigger(v string) predicate.Automation {
	return predicate.Automation(sql.FieldEQ(FieldTrigger, v))
}

// Manifest applies equality check predicate on the "manifest" field. It's identical to ManifestEQ.
func Manifest(v string) predicate.Automation {
	return predicate.Automation(sql.FieldEQ(FieldManifest, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Automation {
	return predicate.Automation(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Automation {
	return predicate.Automation(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Automation {
	return predicate.Automation(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Automation {
	return predicate.Automation(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Automation {
	return predicate.Automation(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Automation {
	return predicate.Automation(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Automation {
	return predicate.Automation(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Automation {
	return predicate.Automation(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Automation {
	return predicate.Automation(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Automation {
	return predicate.Automation(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Automation {
	return predicate.Automation(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Automation {
	return predicate.Automation(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Automation {
	return predicate.Automation(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Automation {
	return predicate.Automation(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Automation {
	return predicate.Automation(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Automation {
	return predicate.Automation(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Automation {
	return predicate.Automation(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Automation {
	return predicate.Automation(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Automation {
	return predicate.Automation(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Automation {
	return predicate.Automation(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Automation {
	return predicate.Automation(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Automation {
	return predicate.Automation(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Automation {
	return predicate.Automation(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Automation {
	return predicate.Automation(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Automation {
	return predicate.Automation(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Automation {
	return predicate.Automation(sql.FieldContainsFold(FieldDescription, v))
}

// TriggerEQ applies the EQ predicate on the "trigger" field.
func TriggerEQ(v string) predicate.Automation {
	return predicate.Automation(sql.FieldEQ(FieldTrigger, v))
}

// TriggerNEQ applies the NEQ predicate on the "trigger" field.
func TriggerNEQ(v string) predicate.Automation {
	return predicate.Automation(sql.FieldNEQ(FieldTrigger, v))
}

// TriggerIn applies the In predicate on the "trigger" field.
func TriggerIn(vs ...string) predicate.Automation {
	return predicate.Automation(sql.FieldIn(FieldTrigger, vs...))
}

// TriggerNotIn applies the NotIn predicate on the "trigger" field.
func TriggerNotIn(vs ...string) predicate.Automation {
	return predicate.Automation(sql.FieldNotIn(FieldTrigger, vs...))
}

// TriggerGT applies the GT predicate on the "trigger" field.
func TriggerGT(v string) predicate.Automation {
	return predicate.Automation(sql.FieldGT(FieldTrigger, v))
}

// TriggerGTE applies the GTE predicate on the "trigger" field.
func TriggerGTE(v string) predicate.Automation {
	return predicate.Automation(sql.FieldGTE(FieldTrigger, v))
}

// TriggerLT applies the LT predicate on the "trigger" field.
func TriggerLT(v string) predicate.Automation {
	return predicate.Automation(sql.FieldLT(FieldTrigger, v))
}

// TriggerLTE applies the LTE predicate on the "trigger" field.
func TriggerLTE(v string) predicate.Automation {
	return predicate.Automation(sql.FieldLTE(FieldTrigger, v))
}

// TriggerContains applies the Contains predicate on the "trigger" field.
func TriggerContains(v string) predicate.Automation {
	return predicate.Automation(sql.FieldContains(FieldTrigger, v))
}

// TriggerHasPrefix applies the HasPrefix predicate on the "trigger" field.
func TriggerHasPrefix(v string) predicate.Automation {
	return predicate.Automation(sql.FieldHasPrefix(FieldTrigger, v))
}

// TriggerHasSuffix applies the HasSuffix predicate on the "trigger" field.
func TriggerHasSuffix(v string) predicate.Automation {
	return predicate.Automation(sql.FieldHasSuffix(FieldTrigger, v))
}

// TriggerEqualFold applies the EqualFold predicate on the "trigger" field.
func TriggerEqualFold(v string) predicate.Automation {
	return predicate.Automation(sql.FieldEqualFold(FieldTrigger, v))
}

// TriggerContainsFold applies the ContainsFold predicate on the "trigger" field.
func TriggerContainsFold(v string) predicate.Automation {
	return predicate.Automation(sql.FieldContainsFold(FieldTrigger, v))
}

// ManifestEQ applies the EQ predicate on the "manifest" field.
func ManifestEQ(v string) predicate.Automation {
	return predicate.Automation(sql.FieldEQ(FieldManifest, v))
}

// ManifestNEQ applies the NEQ predicate on the "manifest" field.
func ManifestNEQ(v string) predicate.Automation {
	return predicate.Automation(sql.FieldNEQ(FieldManifest, v))
}

// ManifestIn applies the In predicate on the "manifest" field.
func ManifestIn(vs ...string) predicate.Automation {
	return predicate.Automation(sql.FieldIn(FieldManifest, vs...))
}

// ManifestNotIn applies the NotIn predicate on the "manifest" field.
func ManifestNotIn(vs ...string) predicate.Automation {
	return predicate.Automation(sql.FieldNotIn(FieldManifest, vs...))
}

// ManifestGT applies the GT predicate on the "manifest" field.
func ManifestGT(v string) predicate.Automation {
	return predicate.Automation(sql.FieldGT(FieldManifest, v))
}

// ManifestGTE applies the GTE predicate on the "manifest" field.
func ManifestGTE(v string) predicate.Automation {
	return predicate.Automation(sql.FieldGTE(FieldManifest, v))
}

// ManifestLT applies the LT predicate on the "manifest" field.
func ManifestLT(v string) predicate.Automation {
	return predicate.Automation(sql.FieldLT(FieldManifest, v))
}

// ManifestLTE applies the LTE predicate on the "manifest" field.
func ManifestLTE(v string) predicate.Automation {
	return predicate.Automation(sql.FieldLTE(FieldManifest, v))
}

// ManifestContains applies the Contains predicate on the "manifest" field.
func ManifestContains(v string) predicate.Automation {
	return predicate.Automation(sql.FieldContains(FieldManifest, v))
}

// ManifestHasPrefix applies the HasPrefix predicate on the "manifest" field.
func ManifestHasPrefix(v string) predicate.Automation {
	return predicate.Automation(sql.FieldHasPrefix(FieldManifest, v))
}

// ManifestHasSuffix applies the HasSuffix predicate on the "manifest" field.
func ManifestHasSuffix(v string) predicate.Automation {
	return predicate.Automation(sql.FieldHasSuffix(FieldManifest, v))
}

// ManifestEqualFold applies the EqualFold predicate on the "manifest" field.
func ManifestEqualFold(v string) predicate.Automation {
	return predicate.Automation(sql.FieldEqualFold(FieldManifest, v))
}

// ManifestContainsFold applies the ContainsFold predicate on the "manifest" field.
func ManifestContainsFold(v string) predicate.Automation {
	return predicate.Automation(sql.FieldContainsFold(FieldManifest, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Automation) predicate.Automation {
	return predicate.Automation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Automation) predicate.Automation {
	return predicate.Automation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Automation) predicate.Automation {
	return predicate.Automation(sql.NotPredicates(p))
}
