// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.pitagora/pkg/ent/automation"
	"github.pitagora/pkg/ent/predicate"
)

// AutomationUpdate is the builder for updating Automation entities.
type AutomationUpdate struct {
	config
	hooks    []Hook
	mutation *AutomationMutation
}

// Where appends a list predicates to the AutomationUpdate builder.
func (au *AutomationUpdate) Where(ps ...predicate.Automation) *AutomationUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetDescription sets the "description" field.
func (au *AutomationUpdate) SetDescription(s string) *AutomationUpdate {
	au.mutation.SetDescription(s)
	return au
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (au *AutomationUpdate) SetNillableDescription(s *string) *AutomationUpdate {
	if s != nil {
		au.SetDescription(*s)
	}
	return au
}

// SetTrigger sets the "trigger" field.
func (au *AutomationUpdate) SetTrigger(s string) *AutomationUpdate {
	au.mutation.SetTrigger(s)
	return au
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (au *AutomationUpdate) SetNillableTrigger(s *string) *AutomationUpdate {
	if s != nil {
		au.SetTrigger(*s)
	}
	return au
}

// SetManifest sets the "manifest" field.
func (au *AutomationUpdate) SetManifest(s string) *AutomationUpdate {
	au.mutation.SetManifest(s)
	return au
}

// SetNillableManifest sets the "manifest" field if the given value is not nil.
func (au *AutomationUpdate) SetNillableManifest(s *string) *AutomationUpdate {
	if s != nil {
		au.SetManifest(*s)
	}
	return au
}

// Mutation returns the AutomationMutation object of the builder.
func (au *AutomationUpdate) Mutation() *AutomationMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AutomationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AutomationUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AutomationUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AutomationUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

func (au *AutomationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(automation.Table, automation.Columns, sqlgraph.NewFieldSpec(automation.FieldID, field.TypeInt64))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Description(); ok {
		_spec.SetField(automation.FieldDescription, field.TypeString, value)
	}
	if value, ok := au.mutation.Trigger(); ok {
		_spec.SetField(automation.FieldTrigger, field.TypeString, value)
	}
	if value, ok := au.mutation.Manifest(); ok {
		_spec.SetField(automation.FieldManifest, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{automation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AutomationUpdateOne is the builder for updating a single Automation entity.
type AutomationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AutomationMutation
}

// SetDescription sets the "description" field.
func (auo *AutomationUpdateOne) SetDescription(s string) *AutomationUpdateOne {
	auo.mutation.SetDescription(s)
	return auo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (auo *AutomationUpdateOne) SetNillableDescription(s *string) *AutomationUpdateOne {
	if s != nil {
		auo.SetDescription(*s)
	}
	return auo
}

// SetTrigger sets the "trigger" field.
func (auo *AutomationUpdateOne) SetTrigger(s string) *AutomationUpdateOne {
	auo.mutation.SetTrigger(s)
	return auo
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (auo *AutomationUpdateOne) SetNillableTrigger(s *string) *AutomationUpdateOne {
	if s != nil {
		auo.SetTrigger(*s)
	}
	return auo
}

// SetManifest sets the "manifest" field.
func (auo *AutomationUpdateOne) SetManifest(s string) *AutomationUpdateOne {
	auo.mutation.SetManifest(s)
	return auo
}

// SetNillableManifest sets the "manifest" field if the given value is not nil.
func (auo *AutomationUpdateOne) SetNillableManifest(s *string) *AutomationUpdateOne {
	if s != nil {
		auo.SetManifest(*s)
	}
	return auo
}

// Mutation returns the AutomationMutation object of the builder.
func (auo *AutomationUpdateOne) Mutation() *AutomationMutation {
	return auo.mutation
}

// Where appends a list predicates to the AutomationUpdate builder.
func (auo *AutomationUpdateOne) Where(ps ...predicate.Automation) *AutomationUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AutomationUpdateOne) Select(field string, fields ...string) *AutomationUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Automation entity.
func (auo *AutomationUpdateOne) Save(ctx context.Context) (*Automation, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AutomationUpdateOne) SaveX(ctx context.Context) *Automation {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AutomationUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AutomationUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auo *AutomationUpdateOne) sqlSave(ctx context.Context) (_node *Automation, err error) {
	_spec := sqlgraph.NewUpdateSpec(automation.Table, automation.Columns, sqlgraph.NewFieldSpec(automation.FieldID, field.TypeInt64))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Automation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, automation.FieldID)
		for _, f := range fields {
			if !automation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != automation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Description(); ok {
		_spec.SetField(automation.FieldDescription, field.TypeString, value)
	}
	if value, ok := auo.mutation.Trigger(); ok {
		_spec.SetField(automation.FieldTrigger, field.TypeString, value)
	}
	if value, ok := auo.mutation.Manifest(); ok {
		_spec.SetField(automation.FieldManifest, field.TypeString, value)
	}
	_node = &Automation{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{automation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
