// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.pitagora/pkg/ent/automation"
)

// Automation is the model entity for the Automation schema.
type Automation struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Trigger holds the value of the "trigger" field.
	Trigger string `json:"trigger,omitempty"`
	// Manifest holds the value of the "manifest" field.
	Manifest     string `json:"manifest,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Automation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case automation.FieldID:
			values[i] = new(sql.NullInt64)
		case automation.FieldName, automation.FieldDescription, automation.FieldTrigger, automation.FieldManifest:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Automation fields.
func (a *Automation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case automation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int64(value.Int64)
		case automation.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				a.Name = value.String
			}
		case automation.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				a.Description = value.String
			}
		case automation.FieldTrigger:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger", values[i])
			} else if value.Valid {
				a.Trigger = value.String
			}
		case automation.FieldManifest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manifest", values[i])
			} else if value.Valid {
				a.Manifest = value.String
			}
		default:
			a.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Automation.
// This includes values selected through modifiers, order, etc.
func (a *Automation) Value(name string) (ent.Value, error) {
	return a.selectValues.Get(name)
}

// Update returns a builder for updating this Automation.
// Note that you need to call Automation.Unwrap() before calling this method if this Automation
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Automation) Update() *AutomationUpdateOne {
	return NewAutomationClient(a.config).UpdateOne(a)
}

// Unwrap unwraps the Automation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Automation) Unwrap() *Automation {
	_tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Automation is not a transactional entity")
	}
	a.config.driver = _tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Automation) String() string {
	var builder strings.Builder
	builder.WriteString("Automation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", a.ID))
	builder.WriteString("name=")
	builder.WriteString(a.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(a.Description)
	builder.WriteString(", ")
	builder.WriteString("trigger=")
	builder.WriteString(a.Trigger)
	builder.WriteString(", ")
	builder.WriteString("manifest=")
	builder.WriteString(a.Manifest)
	builder.WriteByte(')')
	return builder.String()
}

// Automations is a parsable slice of Automation.
type Automations []*Automation
