// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.pitagora/pkg/ent/predicate"
	"github.pitagora/pkg/ent/procedure"
)

// ProcedureUpdate is the builder for updating Procedure entities.
type ProcedureUpdate struct {
	config
	hooks    []Hook
	mutation *ProcedureMutation
}

// Where appends a list predicates to the ProcedureUpdate builder.
func (pu *ProcedureUpdate) Where(ps ...predicate.Procedure) *ProcedureUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetDescription sets the "description" field.
func (pu *ProcedureUpdate) SetDescription(s string) *ProcedureUpdate {
	pu.mutation.SetDescription(s)
	return pu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (pu *ProcedureUpdate) SetNillableDescription(s *string) *ProcedureUpdate {
	if s != nil {
		pu.SetDescription(*s)
	}
	return pu
}

// SetMetadata sets the "metadata" field.
func (pu *ProcedureUpdate) SetMetadata(s string) *ProcedureUpdate {
	pu.mutation.SetMetadata(s)
	return pu
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (pu *ProcedureUpdate) SetNillableMetadata(s *string) *ProcedureUpdate {
	if s != nil {
		pu.SetMetadata(*s)
	}
	return pu
}

// SetManifest sets the "manifest" field.
func (pu *ProcedureUpdate) SetManifest(s string) *ProcedureUpdate {
	pu.mutation.SetManifest(s)
	return pu
}

// SetNillableManifest sets the "manifest" field if the given value is not nil.
func (pu *ProcedureUpdate) SetNillableManifest(s *string) *ProcedureUpdate {
	if s != nil {
		pu.SetManifest(*s)
	}
	return pu
}

// Mutation returns the ProcedureMutation object of the builder.
func (pu *ProcedureUpdate) Mutation() *ProcedureMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProcedureUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProcedureUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProcedureUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProcedureUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *ProcedureUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(procedure.Table, procedure.Columns, sqlgraph.NewFieldSpec(procedure.FieldID, field.TypeInt64))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Description(); ok {
		_spec.SetField(procedure.FieldDescription, field.TypeString, value)
	}
	if value, ok := pu.mutation.Metadata(); ok {
		_spec.SetField(procedure.FieldMetadata, field.TypeString, value)
	}
	if value, ok := pu.mutation.Manifest(); ok {
		_spec.SetField(procedure.FieldManifest, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{procedure.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// ProcedureUpdateOne is the builder for updating a single Procedure entity.
type ProcedureUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProcedureMutation
}

// SetDescription sets the "description" field.
func (puo *ProcedureUpdateOne) SetDescription(s string) *ProcedureUpdateOne {
	puo.mutation.SetDescription(s)
	return puo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (puo *ProcedureUpdateOne) SetNillableDescription(s *string) *ProcedureUpdateOne {
	if s != nil {
		puo.SetDescription(*s)
	}
	return puo
}

// SetMetadata sets the "metadata" field.
func (puo *ProcedureUpdateOne) SetMetadata(s string) *ProcedureUpdateOne {
	puo.mutation.SetMetadata(s)
	return puo
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (puo *ProcedureUpdateOne) SetNillableMetadata(s *string) *ProcedureUpdateOne {
	if s != nil {
		puo.SetMetadata(*s)
	}
	return puo
}

// SetManifest sets the "manifest" field.
func (puo *ProcedureUpdateOne) SetManifest(s string) *ProcedureUpdateOne {
	puo.mutation.SetManifest(s)
	return puo
}

// SetNillableManifest sets the "manifest" field if the given value is not nil.
func (puo *ProcedureUpdateOne) SetNillableManifest(s *string) *ProcedureUpdateOne {
	if s != nil {
		puo.SetManifest(*s)
	}
	return puo
}

// Mutation returns the ProcedureMutation object of the builder.
func (puo *ProcedureUpdateOne) Mutation() *ProcedureMutation {
	return puo.mutation
}

// Where appends a list predicates to the ProcedureUpdate builder.
func (puo *ProcedureUpdateOne) Where(ps ...predicate.Procedure) *ProcedureUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProcedureUpdateOne) Select(field string, fields ...string) *ProcedureUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Procedure entity.
func (puo *ProcedureUpdateOne) Save(ctx context.Context) (*Procedure, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProcedureUpdateOne) SaveX(ctx context.Context) *Procedure {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProcedureUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProcedureUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *ProcedureUpdateOne) sqlSave(ctx context.Context) (_node *Procedure, err error) {
	_spec := sqlgraph.NewUpdateSpec(procedure.Table, procedure.Columns, sqlgraph.NewFieldSpec(procedure.FieldID, field.TypeInt64))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Procedure.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, procedure.FieldID)
		for _, f := range fields {
			if !procedure.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != procedure.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Description(); ok {
		_spec.SetField(procedure.FieldDescription, field.TypeString, value)
	}
	if value, ok := puo.mutation.Metadata(); ok {
		_spec.SetField(procedure.FieldMetadata, field.TypeString, value)
	}
	if value, ok := puo.mutation.Manifest(); ok {
		_spec.SetField(procedure.FieldManifest, field.TypeString, value)
	}
	_node = &Procedure{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{procedure.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
