// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.pitagora/pkg/ent/procedure"
)

// Procedure is the model entity for the Procedure schema.
type Procedure struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata string `json:"metadata,omitempty"`
	// Manifest holds the value of the "manifest" field.
	Manifest     string `json:"manifest,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Procedure) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case procedure.FieldID:
			values[i] = new(sql.NullInt64)
		case procedure.FieldName, procedure.FieldDescription, procedure.FieldMetadata, procedure.FieldManifest:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Procedure fields.
func (pr *Procedure) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case procedure.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pr.ID = int64(value.Int64)
		case procedure.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				pr.Name = value.String
			}
		case procedure.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				pr.Description = value.String
			}
		case procedure.FieldMetadata:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value.Valid {
				pr.Metadata = value.String
			}
		case procedure.FieldManifest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manifest", values[i])
			} else if value.Valid {
				pr.Manifest = value.String
			}
		default:
			pr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Procedure.
// This includes values selected through modifiers, order, etc.
func (pr *Procedure) Value(name string) (ent.Value, error) {
	return pr.selectValues.Get(name)
}

// Update returns a builder for updating this Procedure.
// Note that you need to call Procedure.Unwrap() before calling this method if this Procedure
// was returned from a transaction, and the transaction was committed or rolled back.
func (pr *Procedure) Update() *ProcedureUpdateOne {
	return NewProcedureClient(pr.config).UpdateOne(pr)
}

// Unwrap unwraps the Procedure entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pr *Procedure) Unwrap() *Procedure {
	_tx, ok := pr.config.driver.(*txDriver)
	if !ok {
		panic("ent: Procedure is not a transactional entity")
	}
	pr.config.driver = _tx.drv
	return pr
}

// String implements the fmt.Stringer.
func (pr *Procedure) String() string {
	var builder strings.Builder
	builder.WriteString("Procedure(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pr.ID))
	builder.WriteString("name=")
	builder.WriteString(pr.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(pr.Description)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(pr.Metadata)
	builder.WriteString(", ")
	builder.WriteString("manifest=")
	builder.WriteString(pr.Manifest)
	builder.WriteByte(')')
	return builder.String()
}

// Procedures is a parsable slice of Procedure.
type Procedures []*Procedure
